import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import SectionIntroduction from "../components/SectionIntroduction/SectionIntroduction";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trappe Expert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <SectionIntroduction />
      </main>
    </div>
  );
}
