import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import SectionIntroduction from "../components/SectionIntroduction/SectionIntroduction";
import SectionMainProducts from "../components/SectionMainProducts/SectionMainProducts";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Trappe Expert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <SectionIntroduction />
        <SectionMainProducts />
        <section>Section - Mode de livraison</section>
        <section>Section - Installation par nos équipte</section>
      </main>

      <Footer />
      <div style={{ height: "100vh", backgroundColor: "grey" }}></div>
    </div>
  );
}
